# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db50a467ceab4cbcef483e251d31092e"
name = "payment-customisation"
handle = "payment-customisation-10"
application_url = "https://working-exciting-panama-entrance.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wad-test123.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://working-exciting-panama-entrance.trycloudflare.com/auth/callback",
  "https://working-exciting-panama-entrance.trycloudflare.com/auth/shopify/callback",
  "https://working-exciting-panama-entrance.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
